### ISSUE TITLE
Data used for training

### ISSUE THREAD

**Issue by pbk0** [gabzai/Methodology-for-efficient-CNN-architectures-in-SCA#1]
Hi,

First of all thanks a lot for sharing your work and helping out the community.

I have one request:

Since the code is complete can you supply the *.npy files for all dataset? Or maybe share scripts used to generate that data.

I do not want to assume things to generate *.npy files on my own. It will just help in speeding up things. Also, share the hash of datasets.

Nonetheless, for ASCAD case I am able to run as it works directly on the datasets provided.

**Comment by gabzai** [comment]
Hi,

Thanks for your suggestion ! We will add our *.npy files asap!

Regards,
