### ISSUE TITLE
Hi, I cannot run your AES_RD

### ISSUE THREAD

**Issue by HuiminLiCandicehehe** [gabzai/Methodology-for-efficient-CNN-architectures-in-SCA#2]
Dear Gabriel,
    Thanks for your paper and code.
   AES_RD cannot be run because there is something wrong with the dataset.  There is no profiling_traces_AES_RD.npy,profiling_plaintext_AES_RD.npy and no profiling_labels_AES_RD.npy.

Best wishes,
hm

**Comment by gabzai** [comment]
Dear Candice,

Thanks for your report. We fixed the problem.

Kinds Regards
