### ISSUE TITLE
Cannot load the key.npy of AES_RD_dataset

### ISSUE THREAD

**Issue by HuiminLiCandicehehe** [gabzai/Methodology-for-efficient-CNN-architectures-in-SCA#3]
Dear Gabriel,
Thanks for quick reply.
Now I can load the files you just uploaded( profiling_traces_AES_RD.npy,profiling_plaintext_AES_RD.npy and no profiling_labels_AES_RD.npy). But I can not load the key.npy.

**Comment by gabzai** [comment]
Dear Candice,

Yes, thanks again for your report. We fixed the problem.
