### ISSUE TITLE
DPAv4 dataset

### ISSUE THREAD

**Issue by pbk0** [gabzai/Methodology-for-efficient-CNN-architectures-in-SCA#4]
Thanks for uploading datasets. I need one more help.

There are 16 single key datasets for DPAv4.2 as provided here http://www.dpacontest.org/v4/42_traces.php
But I assume you have provided only one out of 16 datasets.

Can I have datasets for all 16 keys.
Or else share below steps:
+ how 4000 samples were selected
+ normalization steps used to convert traces to float type

Apart from that if possible maybe you can just add preprocessing steps for all other datasets. For ASCAD it is clear but for other datasets, it is not clear.

Sorry if I have missed reading some literature which states the extraction steps for the datasets.

**Comment by zL1nX** [comment]
Hello! I also have the same issue about how the samples were generated. I already unpack the raw traces but have no idea how to generate the same data as in the profiling_traces_dpav4.npy and profiling_labels_dpav4.npy. Should I use PCA or KDA or other techniques? 

And what does the labels stands for?  Are they the intermediate value of the first round SBox masked output for the first key byte?

Thank you!

**Comment by gabzai** [comment]
Hi zL1nX,

In order to find the correct range of samples, you have to perform a leakage analysis (e.g. SNR) on the first round of AES such that the following sensitive information should be considered:
- Y1 = Sbox[P[0] xor k[0]] xor M[offset[]] with 
        - P[0] is the first plaintext byte
        - k[0] is the first key byte
        - M[offset[]] is the first mask byte such that its index is defined by an offset array
        
I recommend you to read: http://www.dpacontest.org/v4/42_doc.php and http://www.dpacontest.org/v4/data/v4_2/article_implem_dpav42.pdf  

No PCA, KDA or other techniques are mandatory to generate the same data as in profiling_traces_dpav4.npy and profiling_labels_dpav4.npy files.

**Comment by lambdaupb** [comment]
I was asking myself as well. I compared the traces to the raw traces and found the following:

The traces seem to be just a window taken from the raw traces, without post-processing.

By searching for an overlap I found the following offsets for the window:

trace[335_000 : 335_000+2000]
trace[353_000 : 353_000+2000]

which means the first 2000 samples are from offset 353_000 and the second 2000 samples are from offset 353_000.

The dataset seems to be entirely of key k00, 4000 profiling and 1000 attack.

This also means the profiling and attack traces have the same key.

**Comment by lambdaupb** [comment]
(sorry for the earlier, deleted comment, I had a mixup)

I had the same question and investigated a bit.

The DPAv4.2 dataset used here is a 4000 sample window from the raw trace.

Through a cross-correlation analysis on re-normalized data, I found the offset of the window.


![index](https://user-images.githubusercontent.com/1890613/222927408-1d538eb0-dd4d-481a-b7e4-e070a1892032.png)

The window is [270_000 : 274_000]

The traces are normalized to approx. the interval of (-0.06, +0.06), which seems odd.
I get a pretty well matching scaling by dividing by the variance.

![scaling](https://user-images.githubusercontent.com/1890613/222927467-3fd97541-7cd6-4118-ba16-eb32cab0e888.png)


All the data has the same key, key k00 from the raw dataset.
This also means that the profiling and attack data share the same key.

So to reproduce the data from the DPAv4.2 raw data, the following steps will produce something very similar:
```python
traces = np.array(raw_traces[:, 270_000 : 274_000], dtype=np.float32)
traces_normed = traces / np.var(traces)
```
